# frozen_string_literal: true

source "https://rubygems.org"

#gem "rails"
#gem "jekyll"
gem "github-pages", "~> 226", group: :jekyll_plugins

gem "webrick", "~> 1.7"

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
end


gem 'wdm', '>= 0.1.0' if Gem.win_platform?
